Story_7/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accordion.urls')),
    path('libary/', include('libary.urls')),
    path('', include('login.urls')),
    
]

accordion/urls.py
from django.urls import path
from . import views



 
urlpatterns = [
    path('home/', views.home, name='accordions'),
]

libary/urls.py
from django.urls import path
from . import views

app_name = 'libary'

urlpatterns = [
    path('', views.libarry, name='libarry'),
    path('books/', views.books, name="books"),
]

login/urls.py
from django.urls import path
from . import views
from django.contrib.auth import logout
from django.contrib.auth import views as auth_views

app_name = 'login'

urlpatterns = [
    path('welcome/', views.welcome, name='welcome'),
    path('login/', views.loginPage, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutPage , name='logout'),
]

accordion/models.py
from django.db import models

# Create your models here.

libary/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

migrate/models.py
from django.db import models

# Create your models here.

accordion/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

libary/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
import requests
import json

# Create your views here.
def libarry(request):
    return render(request, "libary.html")

def books(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    data_books = json.loads(ret.content)
    return JsonResponse(data_books, safe=False)

login/views.py
from django.shortcuts import render, HttpResponse, redirect, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required(login_url='/login')
def welcome(request):
    return render(request, "welcome.html")

def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('login:welcome')
        else:
            messages.info(request, 'Username OR password is incorrect')

    context = {}
    return render(request, 'login.html', context)

def register(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account has been created')
            return redirect('login:login')
    context = {'form': form }
    return render(request, 'register.html', context)

def logoutPage(request):
    logout(request)
    return HttpResponseRedirect('/login')

migrate/views.py
from django.shortcuts import render

# Create your views here.

accordion/templates/home.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <title>Accordion</title>
   
    
    
</head>
<body>
    <div class="wrapper">
  <div class="accordion_wrap ">
        <div class="accordion_header">
            Tentang Saya
            <a href="#" class="up">Up</a>
            <a href="#" class="down">Down</a>
        </div>
        <div class="accordion_body">
          <p>Saya Aimar Fikri Salafi, Saya suka bermain game rpg dan turn base. Saya berumur 18, tapi wajahnya dah tua jika ingin lebih tau tentang saya bisa ke <a href="http://website-aimarv2.herokuapp.com/ ">sini</a>  </p>
        </div>
  </div>
  <div class="accordion_wrap ">
    <div class="accordion_header">
      organisai
      <a href="#" class="up">Up</a>
      <a href="#" class="down">Down</a>
    </div>
    <div class="accordion_body">
        <li> IGI COMPFEST</li>
        <li> PERAK divisi Games</li>
        <li> ROHIS SMAN 78 Jakarta</li>
    </div>
  </div>
  <div class="accordion_wrap ">
    <div class="accordion_header">
        Prestasi
        <a href="#" class="up">Up</a>
        <a href="#" class="down">Down</a>
    </div>
    <div class="accordion_body">
        <li> Udah ke rank Archon 1</li>
        <li> Lomba Masak saat SMA</li>
        <li> Masih Mencari Sampai sekarang</li>
    </div>
  </div>
  <div class="accordion_wrap ">
    <div class="accordion_header">
    Aktivitas Sehari-hari
    <a href="#" class="up">Up</a>
  <a href="#" class="down">Down</a>
  </div>
  <div class="accordion_body">
          <li> Main Game</li>
          <li> Makan</li>
          <li> olahraga</li>
          <li> tidur selama 2 jam per 4 jam sekali</li>
  </div>
  </div>

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
       <script src="{% static '/js/style.js' %}"></script>
  
</body>
</html>

libary/templates/libary.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style8.css' %}">
    <title>Perpustakaan sukajaya</title>
</head>
<body>

   <section class="Perpus_tittle">
        <h2>Perpustakaan sukajaya</h2>
        <p>selamat datang di perpustakaan sukajaya</p>
    </section>
    <section class="containerSearchBox">
        <input id="keyword" placeholder="Masukan Nama buku" class="form-control">
        <button id="button_cari" type="button" class="btn btn-outline-primary">Cari </button>
    </section>
    <section class="containerbooks">
    <div class="table-responsive" id="tableku">
        <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">No</th>
          <th scope="col">Cover</th>
          <th scope="col">Judul</th>
          <th scope="col">Penulis</th>
        </tr>
      </thead>
      <tbody class = "baris_tabel">
      </tbody>
    </table>
    </div>
    </section>
    
   


 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script  src = "{% static '/js/jslib.js' %}" ></script>
</body>
</html>

login/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style9.css' %}">
     {% block title%}

    {% endblock %}

</head>
<body>
 {% block content %}

    {% endblock %}

   
   


 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script  src = "{% static '/js/jslib.js' %}" ></script>
</body>
</html>

login/templates/login.html
{% extends 'base.html' %}
{% block title  %}
<title>Loginnya disini gan</title>
{% endblock %}

{% block content %}
 <section class="loginContainer">
     <header class="loginHead">
        Welcome to the login page
    </header>
        <form method="POST" action="" id="formLogin">
            {% csrf_token %}
            <input type="text" name="username" class="form-control" placeholder="Username">
            <input type="password" name="password" class="form-control" placeholder="Password">
            <button type="submit" class="btn btn-outline-primary">Submit</button>
        </form>
     <div>
         Don't have an account? <a href="{% url 'login:register' %}"> Sign Up </a>
    </div>
     {% for message in messages %}
         <p>{{ message }}</p>
     {% endfor %}
    </section>
{% endblock %}

login/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="registerContainer">
        <form method="POST" action="">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-primary">Submit</button>
        </form>
    </section>
{% endblock %}

login/templates/welcome.html
{% extends 'base.html' %}

{% block title  %}
<title>ini welcome!</title>
{% endblock %}


{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center px-2" id="homeC">
        <div class="col-10 pt-2">
            
            <h1 class="mt-4 pt-2">Welcome, {{ request.user }}</h1>
            
        </div>

         <a href="{% url 'login:logout' %}"><button class="btn btn-danger btn-sm" id="buttonLogin">Logout</button></a>
    </div>
</div>

{% endblock %}